export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_TWITTER_START = 'AUTH_TWITTER_START';
export const AUTH_TWITTER_SUCCESS = 'AUTH_TWITTER_SUCCESS';
export const AUTH_TWITTER_FAIL = 'AUTH_TWITTER_FAIL';

export const AUTH_GITHUB_START = 'AUTH_GITHUB_START';
export const AUTH_GITHUB_SUCCESS = 'AUTH_GITHUB_SUCCESS';
export const AUTH_GITHUB_FAIL = 'AUTH_GITHUB_FAIL';

export const FETCH_GITHUB_DETAILS_SUCCESS = 'FETCH_GITHUB_DETAILS_SUCCESS';
export const FETCH_GITHUB_DETAILS_FAIL = 'FETCH_GITHUB_DETAILS_FAIL';
export const FETCH_GITHUB_DETAILS_START = 'FETCH_GITHUB_DETAILS_START';

export const AUTH_LINKEDIN_START = 'AUTH_LINKEDIN_START';
export const AUTH_LINKEDIN_SUCCESS = 'AUTH_LINKEDIN_SUCCESS';
export const AUTH_LINKEDIN_FAIL = 'AUTH_LINKEDIN_FAIL';

export const AUTH_BASICAUTH_START = 'AUTH_BASICAUTH_START';
export const AUTH_BASICAUTH_SUCCESS = 'AUTH_BASICAUTH_SUCCESS';
export const AUTH_BASICAUTH_FAIL = 'AUTH_BASICAUTH_FAIL';

export const FETCH_LINKEDIN_DETAILS_SUCCESS = 'FETCH_LINKEDIN_DETAILS_SUCCESS';
export const FETCH_LINKEDIN_DETAILS_FAIL = 'FETCH_LINKEDIN_DETAILS_FAIL';
export const FETCH_LINKEDIN_DETAILS_START = 'FETCH_LINKEDIN_DETAILS_START';

export const UPDATE_USER_INFO_START = 'UPDATE_USER_INFO_START';
export const UPDATE_USER_INFO_FAIL = 'UPDATE_USER_INFO_FAIL';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';

export const SET_PASSWORD_START = 'SET_PASSWORD_START';
export const SET_PASSWORD_FAIL = 'SET_PASSWORD_FAIL';
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS';

export const SET_MOBILE_NO_START = 'SET_MOBILE_NO_START';
export const SET_MOBILE_NO_FAIL = 'SET_MOBILE_NO_FAIL';
export const SET_MOBILE_NO_SUCCESS = 'SET_MOBILE_NO_SUCCESS';